version: '3.8'

services:
  user_management:
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.scope=admin"
    image: ghcr.io/stevensblueprint/user_management:latest
    ports:
      - "172.17.0.1:8080:8080"
  blueprint_admin:
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.scope=admin"
    image: ghcr.io/stevensblueprint/blueprint_admin:latest
    ports:
      - "172.17.0.1:3005:80"
  wt:
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.scope=admin"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope admin
